[theme]
# Primary accent color for interactive elements - Navy Blue
primaryColor = "#283593"

# Background color for the main content area - True Black
backgroundColor = "#000000"

# Background color used for the sidebar and most interactive widgets - Navy Blue
secondaryBackgroundColor = "#1A237E"

# Color used for almost all text - Clean White
textColor = "#FFFFFF"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# Default: "sans serif"
font = "sans serif"
[global]
dataFrameSerialization = "legacy"